language: java
jdk: oraclejdk7
before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r22.6-linux.tgz
    - tar xzf android-sdk_r22.6-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

    # Install required Android components.
    - echo y | android update sdk --filter platform-tools,build-tools-19.0.3,sysimg-17,android-17,extra-android-support,extra-android-m2repository --no-ui --force
    - ls -lR ${ANDROID_HOME}/extras

    # Create and start emulator
    - echo no | android create avd --force -n test -t android-17
    - emulator -avd test -no-skin -no-audio -no-window &

before_script:
    # Make sure the emulator has started before running tests
    - chmod +x wait-for-emulator
    - ./wait-for-emulator

script:
    - TERM=dumb ./gradlew build
    - TERM=dumb ./gradlew :library:connectedCheck

after_success:
    - TERM=dumb ./gradlew -p library -b library/coverage.gradle coveralls
